### ISSUE TITLE
Wrong traffic light with REALLY low throuput

### ISSUE THREAD

**Issue by rstockm** [holgerkrupp/networkLight#11]
If the speed drops under 1MBps, the light shows green instead of red:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/3195116/197417994-7d3d835e-3ad6-4848-8177-b6e6bf0e5996.png">

And the history is wrong, too:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/3195116/197418035-41a93d1f-79d7-4166-b0e8-1333d060292a.png">

**Comment by holgerkrupp** [comment]
Should ne solved by using the JSON output (https://github.com/holgerkrupp/networkLight/issues/5), but I currently don't understand how to calculate speed with the given data.

**Comment by holgerkrupp** [comment]
I've added a quick hack in 1.0.5 to divide the Speeds by 1000 if the Unit is Kbps.
