### ISSUE TITLE
Width of settings page

### ISSUE THREAD

**Issue by rstockm** [holgerkrupp/networkLight#9]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/3195116/197384854-ed3c213f-737c-45bb-aa49-ac366bde5f7f.png">

50% of the width would be enough for all screens?
And the new "allow notifications" needs some space on the bottom...
The three Limits fields could be much closer to each other

**Comment by holgerkrupp** [comment]
solved with 1.0.4

**Comment by rstockm** [comment]
The History page could be fixed, too...
